title: "Workshops â€“ Methoden & Statistik"
description: "Methoden-Workshops von Arieja Farugie"
url: "https://arifarugie.github.io"   # deine GitHub-Pages-Domain
baseurl: "/workshops"                 # der Name deines Repos, mit / davor

theme: null          # eigenes Theme
markdown: kramdown

# wichtige Verzeichnisse
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
